[tool.poetry]
name = "imgori"
version = "0.2.4"
description = ""
authors = ["narumi <toucans-cutouts0f@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.1.1"
torchvision = "^0.16.1"
torchmetrics = "^1.2.0"
tqdm = "^4.66.1"
loguru = "^0.7.2"
mlconfig = "^0.2.0"
mlflow-skinny = "^2.9.2"
boto3 = "^1.34.15"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.1.0"
ruff = "^0.1.9"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
imgori = "imgori.cli:cli"

[tool.ruff]
exclude = ["build"]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = [
    "B", # flake8-bugbear
    "C", # flake8-comprehensions
    "E", # pycodestyle Error
    # "EM", # flake8-errmsg
    "F", # Pyflakes
    "I", # isort
    "NPY", # NumPy-specific rules
    # "PTH", # flake8-use-pathlib
    # "S", # flake8-bandit
    # "TRY", # raise-vanilla-args
    "UP", # pyupgrade
    "W", # pycodestyle Warning

]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.ruff.isort]
force-single-line = true

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
