device: mps
num_classes: 8
batch_size: 32

trainer:
  name: ImgoriTrainer
  num_epochs: 20
  num_classes: ${num_classes}

train_loader:
  name: ColorJitterDataLoader
  root: data/flip
  phase: train
  batch_size: ${batch_size}
  num_workers: 0

valid_loader:
  name: ColorJitterDataLoader
  root: data/flip
  phase: valid
  batch_size: ${batch_size}
  num_workers: 0

model:
  name: mobilenet_v3
  num_classes: ${num_classes}

optimizer:
  name: Adam
  lr: 1.e-3

scheduler:
  name: StepLR
  step_size: 10

log_params:
  num_epochs: ${trainer.num_epochs}
  batch_size: ${batch_size}
  optimizer: ${optimizer.name}
  lr: ${optimizer.lr}
  scheduler: ${scheduler.name}
  step_size: ${scheduler.step_size}
