device: cuda
batch_size: 256

trainer:
  name: ColorJitterTrainer
  num_epochs: 20

train_loader:
  name: ColorJitterDataLoader
  root: data/widerface/WIDER_train
  batch_size: ${batch_size}
  num_workers: 4

valid_loader:
  name: ColorJitterDataLoader
  root: data/widerface/WIDER_val
  batch_size: ${batch_size}
  num_workers: 4

model:
  name: mobilenet_v3
  num_classes: 4

optimizer:
  name: Adam
  lr: 1.e-3

scheduler:
  name: StepLR
  step_size: 10

log_params:
  num_epochs: ${trainer.num_epochs}
  batch_size: ${batch_size}
  optimizer: ${optimizer.name}
  lr: ${optimizer.lr}
  scheduler: ${scheduler.name}
  step_size: ${scheduler.step_size}
