device: cuda
batch_size: 256

trainer:
  name: MNISTTrainer
  num_epochs: 20
  num_classes: 10

train_loader:
  name: MNISTDataLoader
  root: data
  train: true
  batch_size: ${batch_size}
  num_workers: 0

valid_loader:
  name: MNISTDataLoader
  root: data
  train: false
  batch_size: ${batch_size}
  num_workers: 0

model:
  name: LeNet

optimizer:
  name: Adam
  lr: 1.e-3

scheduler:
  name: StepLR
  step_size: 10

log_params:
  num_epochs: ${trainer.num_epochs}
  batch_size: ${batch_size}
  optimizer: ${optimizer.name}
  lr: ${optimizer.lr}
  scheduler: ${scheduler.name}
  step_size: ${scheduler.step_size}
