device: cuda
num_classes: 8

job:
  name: ClassificationTrainingJob

trainer:
  name: ClassificationTrainer
  num_epochs: 20
  num_classes: ${num_classes}

dataset:
  name: RandomOrientationDataLoader
  root: data/flip
  batch_size: 32
  num_workers: 0

model:
  name: mobilenet_v3
  num_classes: ${num_classes}

optimizer:
  name: Adam
  lr: 1.e-3

scheduler:
  name: StepLR
  step_size: 10

log_params:
  num_epochs: ${trainer.num_epochs}
  batch_size: ${dataset.batch_size}
  optimizer: ${optimizer.name}
  lr: ${optimizer.lr}
  scheduler: ${scheduler.name}
  step_size: ${scheduler.step_size}
